language: elixir
elixir:
        - 1.9
otp_release: 
        - 21.0
script: 
        - MIX_ENV=test mix deps.get
        - MIX_ENV=test mix compile
        - MIX_ENV=test mix test
        - MIX_ENV=test mix coveralls.travis
after_script:
        - MIX_ENV=docs mix deps.get
        - MIX_ENV=docs mix inch.report
